const $=id=>document.getElementById(id),C=$('canvas'),ctx=C.getContext('2d');
const P=['#000000','#ffffff','#ff3b30','#9cef00','#08c65b','#ab49df','#12b9e8','#ff2b82','#087aff','#ff8d0a','#ffd00a'];
let view='edit',grid=8,colorGrid='whole',target='fill',tex='none',texOp=1,bg='#ffffff',selected=0,drag=null,history=[],future=[],images=[],selectedImage=-1,fxSlots=[{on:false,type:'GRAIN',amount:.35},{on:false,type:'SCANLINES',amount:.20},{on:false,type:'RGB SHIFT',amount:.15}];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2);
const baseModules=()=>[{id:uid(),name:'LEFT EYE',type:'left-eye',x:2,y:2,w:2,h:2,fill:'#000000',stroke:'#000000',rot:0,texture:'none',canonical:true},{id:uid(),name:'RIGHT EYE',type:'right-eye',x:4,y:2,w:2,h:2,fill:'#ff3b30',stroke:'#ff3b30',rot:0,texture:'none',canonical:true},{id:uid(),name:'MOUTH',type:'mouth',x:2,y:4,w:4,h:2,fill:'#ab49df',stroke:'#ab49df',rot:0,texture:'none',canonical:true},{id:uid(),name:'TORSO',type:'torso',x:2,y:7,w:4,h:1,fill:'#087aff',stroke:'#087aff',rot:0,texture:'none',canonical:true}];
let modules=baseModules();
function snap(v){return Math.round(v*grid)/grid}function snapshot(){history.push(JSON.stringify({modules,bg,texOp}));if(history.length>60)history.shift();future=[]}function restore(s){let o=JSON.parse(s);modules=o.modules;bg=o.bg;texOp=o.texOp;selected=Math.min(selected,Math.max(0,modules.length-1));sync()}
function rr(c,x,y,w,h,r){c.beginPath();if(c.roundRect)c.roundRect(x,y,w,h,Math.min(r,w/2,h/2));else c.rect(x,y,w,h)}
function pathFor(c,m,u){let x=m.x*u,y=m.y*u;c.beginPath();if(m.type==='left-eye'){c.moveTo(x+u,y);c.arc(x+u,y+u,u,-Math.PI/2,Math.PI,false);c.lineTo(x,y);c.closePath()}else if(m.type==='right-eye'){c.arc(x+u,y+u,u,0,Math.PI*2);c.closePath()}else if(m.type==='mouth'){c.moveTo(x+u,y+2*u);c.arc(x+u,y+u,u,Math.PI/2,Math.PI,false);c.lineTo(x,y);c.lineTo(x+4*u,y);c.lineTo(x+4*u,y+u);c.arc(x+3*u,y+u,u,0,Math.PI/2,false);c.closePath()}else if(m.type==='torso'){c.moveTo(x,y+u);c.arc(x+u,y+u,u,Math.PI,Math.PI*1.5,false);c.lineTo(x+3*u,y);c.arc(x+3*u,y+u,u,-Math.PI/2,0,false);c.closePath()}else rr(c,x,y,m.w*u,m.h*u,Math.min(m.w,m.h)*u*.28)}
function pattern(c,type,alpha=.28){let pc=document.createElement('canvas');pc.width=24;pc.height=24;let p=pc.getContext('2d');p.strokeStyle=`rgba(0,0,0,${alpha})`;p.fillStyle=`rgba(0,0,0,${alpha})`;p.lineWidth=1;if(type==='dots'||type==='stipple'){for(let y=4;y<24;y+=8)for(let x=4;x<24;x+=8){p.beginPath();p.arc(x,y,type==='stipple'?1.4:1,0,7);p.fill()}}else if(type==='checker'){p.fillRect(0,0,12,12);p.fillRect(12,12,12,12)}else if(type==='micro grid'){for(let i=0;i<24;i+=6){p.beginPath();p.moveTo(i,0);p.lineTo(i,24);p.stroke();p.beginPath();p.moveTo(0,i);p.lineTo(24,i);p.stroke()}}else if(type==='waves'||type==='zigzag'){for(let y=4;y<24;y+=8){p.beginPath();for(let x=0;x<=24;x+=3)p.lineTo(x,y+Math.sin(x*.6)*2);p.stroke()}}else{let slope=type==='thin diagonal'?-1:1;for(let i=-24;i<48;i+=6){p.beginPath();p.moveTo(i,0);p.lineTo(i+24*slope,24);p.stroke()}}return c.createPattern(pc,'repeat')}
function drawState(c,w,s,includeOverlays=true){c.save();c.clearRect(0,0,w,w);c.fillStyle=s.bg;c.fillRect(0,0,w,w);let u=w/8;(s.modules||[]).forEach(m=>{c.save();pathFor(c,m,u);c.fillStyle=m.fill==='transparent'?'rgba(0,0,0,0)':m.fill;c.fill();if(m.stroke&&m.stroke!=='transparent'){c.strokeStyle=m.stroke;c.lineWidth=Math.max(1,w/800);c.stroke()}if(m.texture&&m.texture!=='none'){pathFor(c,m,u);c.clip();c.globalAlpha=texOp;c.fillStyle=pattern(c,m.texture);c.fillRect(m.x*u,m.y*u,m.w*u,m.h*u)}c.restore()});if(includeOverlays)images.filter(im=>im.visible).forEach(im=>{c.save();c.globalAlpha=im.opacity;c.globalCompositeOperation=im.blend;c.drawImage(im.img,im.x*w,im.y*w,im.w*w,im.h*w);c.restore()});c.restore();if(includeOverlays&&$('fxEnable').checked&&$('liveFx').checked)applyFx(c,w)}
function renderTo(c,w=800,s=null,includeOverlays=true){drawState(c,w,s||{modules,bg},includeOverlays)}
function applyFx(c,w){c.save();fxSlots.forEach(s=>{if(!s.on)return;c.globalAlpha=s.amount;if(s.type==='GRAIN'){for(let i=0;i<w*w/350;i++){c.fillStyle=Math.random()>.5?'#fff':'#000';c.fillRect(Math.random()*w,Math.random()*w,1,1)}}if(s.type==='SCANLINES'){c.fillStyle='#000';for(let y=0;y<w;y+=5)c.fillRect(0,y,w,1)}if(s.type==='RGB SHIFT'){let d=c.getImageData(0,0,w,w),o=c.createImageData(w,w),a=d.data,b=o.data,sh=Math.max(1,Math.floor(w/300));for(let y=0;y<w;y++)for(let x=0;x<w;x++){let i=(y*w+x)*4,ir=(y*w+Math.min(w-1,x+sh))*4,ib=(y*w+Math.max(0,x-sh))*4;b[i]=a[ir];b[i+1]=a[i+1];b[i+2]=a[ib+2];b[i+3]=a[i+3]}c.putImageData(o,0,0)}});c.restore()}
function canonicalOverlay(){let u=100,canon=baseModules();ctx.save();ctx.strokeStyle='rgba(255,45,85,.9)';ctx.fillStyle='rgba(255,45,85,.04)';ctx.lineWidth=2;ctx.setLineDash([7,5]);canon.forEach(m=>{pathFor(ctx,m,u);ctx.fill();ctx.stroke()});ctx.setLineDash([]);ctx.fillStyle='rgba(255,45,85,.85)';ctx.font='bold 12px Arial';canon.forEach(m=>ctx.fillText(`${m.name} · ${m.w}×${m.h}`,m.x*u+6,m.y*u+16));ctx.restore()}
function render(){renderTo(ctx,800);if(view!=='clean'){ctx.save();ctx.strokeStyle=view==='schematic'?'rgba(255,45,85,.28)':'rgba(0,0,0,.12)';ctx.lineWidth=1;for(let i=0;i<=grid;i++){let p=i*800/grid;ctx.beginPath();ctx.moveTo(p,0);ctx.lineTo(p,800);ctx.stroke();ctx.beginPath();ctx.moveTo(0,p);ctx.lineTo(800,p);ctx.stroke()}ctx.restore()}if(view==='schematic')canonicalOverlay();if(view==='edit'&&modules[selected]){let m=modules[selected],u=100;ctx.save();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.setLineDash([8,5]);ctx.strokeRect(m.x*u+2,m.y*u+2,m.w*u-4,m.h*u-4);ctx.strokeStyle='#111';ctx.lineWidth=1;ctx.strokeRect(m.x*u+2,m.y*u+2,m.w*u-4,m.h*u-4);ctx.restore()}}
function sync(){let m=modules[selected];$('selName').textContent=m?m.name:'NONE';$('modCount').textContent=modules.length+' MODULES';$('hex').textContent=$('picker').value.toUpperCase();$('texOpBig').textContent=Math.round(texOp*100)+'%';$('layerCount').textContent=images.length+' LAYERS';$('imgStat').textContent=images.length?images.length+' LAYERS':'NONE';$('imageEmpty').classList.toggle('hidden',images.length>0);$('imgOpBig').textContent=selectedImage>=0?Math.round(images[selectedImage].opacity*100)+'%':'100%';$('blendBig').textContent=selectedImage>=0?images[selectedImage].blend.toUpperCase():'NORMAL';renderLayers();renderFxSlots();render()}
function bindSeg(id,key,fn){$(id).onclick=e=>{let v=e.target.dataset[key];if(v===undefined)return;[...$(id).children].forEach(b=>b.classList.remove('on'));e.target.classList.add('on');fn(v)}}
bindSeg('viewBtns','v',v=>{view=v;$('viewStat').textContent=v.toUpperCase();render()});bindSeg('gridBtns','g',v=>{grid=+v;$('gridBig').textContent=v+'×'+v;$('snapPill').textContent='SNAP '+(8/grid)+' UNIT';render()});bindSeg('colorGridBtns','cg',v=>{colorGrid=v;$('colorGridBig').textContent=v==='whole'?'WHOLE':v+' UNIT'});bindSeg('targetBtns','t',v=>target=v);bindSeg('texTarget','tt',()=>{});bindSeg('layerMode','lm',()=>{});
$('swatches').innerHTML=P.map(p=>`<button class=sw data-col="${p}" style="background:${p}"></button>`).join('');$('swatches').onclick=e=>{if(!e.target.dataset.col)return;$('picker').value=e.target.dataset.col;$('picker').dispatchEvent(new Event('input'))};$('picker').oninput=e=>{snapshot();let m=modules[selected];if(target==='background')bg=e.target.value;else if(m){if(target==='transparent')m.fill='transparent';else m[target]=e.target.value}sync()};
const texNames=['none','dots','diagonal stripes','thin diagonal','crosshatch','micro grid','checker','zigzag','waves','pluses','diamonds','speckle','halftone','brush','scratches','paint streak','stipple'];$('textures').innerHTML=texNames.map((t,i)=>`<button class="tex ${i===0?'on':''}" data-tex="${t}">${t.toUpperCase()}</button>`).join('');$('textures').onclick=e=>{if(!e.target.dataset.tex)return;snapshot();[...$('textures').children].forEach(b=>b.classList.remove('on'));e.target.classList.add('on');tex=e.target.dataset.tex;if(modules[selected])modules[selected].texture=tex;sync()};$('texOp').oninput=e=>{texOp=+e.target.value/100;sync()};
document.querySelector('.modules').onclick=e=>{let b=e.target.closest('[data-add]');if(!b)return;snapshot();let t=b.dataset.add,defs={left:{name:'LEFT EYE',type:'left-eye',x:2,y:2,w:2,h:2},right:{name:'RIGHT EYE',type:'right-eye',x:4,y:2,w:2,h:2},mouth:{name:'MOUTH',type:'mouth',x:2,y:4,w:4,h:2},torso:{name:'TORSO',type:'torso',x:2,y:7,w:4,h:1}},d=defs[t]||defs.mouth,m={id:uid(),...d,fill:P[Math.floor(Math.random()*P.length)],stroke:'#000',rot:0,texture:'none',canonical:true};modules.push(m);selected=modules.length-1;sync()};
$('rotL').onclick=()=>rotate(-90);$('rotR').onclick=()=>rotate(90);function rotate(d){if(!modules[selected])return;snapshot();let m=modules[selected];m.rot=(m.rot+d+360)%360;[m.w,m.h]=[m.h,m.w];m.x=Math.max(0,Math.min(8-m.w,m.x));m.y=Math.max(0,Math.min(8-m.h,m.y));sync()}$('dup').onclick=()=>{if(!modules[selected])return;snapshot();let m=JSON.parse(JSON.stringify(modules[selected]));m.id=uid();m.x=Math.min(8-m.w,m.x+.25);m.y=Math.min(8-m.h,m.y+.25);modules.push(m);selected=modules.length-1;sync()};$('del').onclick=()=>{if(!modules[selected])return;snapshot();modules.splice(selected,1);selected=Math.max(0,selected-1);sync()};
C.onpointerdown=e=>{let r=C.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*8,py=(e.clientY-r.top)/r.height*8;for(let i=modules.length-1;i>=0;i--){let m=modules[i];if(px>=m.x&&px<=m.x+m.w&&py>=m.y&&py<=m.y+m.h){selected=i;snapshot();drag={dx:px-m.x,dy:py-m.y};C.setPointerCapture(e.pointerId);sync();break}}};C.onpointermove=e=>{if(!drag)return;let r=C.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*8,py=(e.clientY-r.top)/r.height*8,m=modules[selected];m.x=Math.max(0,Math.min(8-m.w,snap(px-drag.dx)));m.y=Math.max(0,Math.min(8-m.h,snap(py-drag.dy)));render()};C.onpointerup=()=>drag=null;
$('generate').onclick=()=>{snapshot();modules.forEach(m=>m.fill=P[Math.floor(Math.random()*P.length)]);if(!$('lockBg').checked)bg=P[Math.floor(Math.random()*P.length)];sync()};$('reset').onclick=()=>{snapshot();modules=baseModules();bg='#fff';selected=0;sync()};$('undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify({modules,bg,texOp}));restore(history.pop())};$('redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify({modules,bg,texOp}));restore(future.pop())};
$('fxEnable').onchange=e=>{$('fxState').textContent=e.target.checked?'ON':'OFF';render()};$('preset').onchange=e=>{let p=e.target.value;fxSlots.forEach(s=>s.on=false);if(p!=='CUSTOM')fxSlots[0]={on:true,type:p,amount:.35};sync()};$('savePreset').onclick=()=>localStorage.setItem('opepenPreset',$('presetName').value+':'+JSON.stringify(fxSlots));$('delPreset').onclick=()=>localStorage.removeItem('opepenPreset');function renderFxSlots(){$('fxSlots').innerHTML=fxSlots.map((s,i)=>`<div class=fxslot><div class=ph><label><input type=checkbox data-fxon="${i}" ${s.on?'checked':''}> SLOT ${i+1}</label><span class=bigstat>${Math.round(s.amount*100)}%</span></div><select class=select data-fxtype="${i}"><option ${s.type==='GRAIN'?'selected':''}>GRAIN</option><option ${s.type==='SCANLINES'?'selected':''}>SCANLINES</option><option ${s.type==='RGB SHIFT'?'selected':''}>RGB SHIFT</option></select><input class=slider data-fxamt="${i}" type=range min=0 max=100 value="${Math.round(s.amount*100)}"></div>`).join('')}$('fxSlots').oninput=e=>{let i=e.target.dataset.fxon??e.target.dataset.fxtype??e.target.dataset.fxamt;if(i===undefined)return;i=+i;if(e.target.dataset.fxon!==undefined)fxSlots[i].on=e.target.checked;if(e.target.dataset.fxtype!==undefined)fxSlots[i].type=e.target.value;if(e.target.dataset.fxamt!==undefined)fxSlots[i].amount=+e.target.value/100;render()};
$('loadImages').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{for(const f of e.target.files){let url=URL.createObjectURL(f),im=new Image();await new Promise((res,rej)=>{im.onload=res;im.onerror=rej;im.src=url});images.push({name:f.name,img:im,url,visible:true,opacity:1,blend:'source-over',x:0,y:0,w:1,h:1})}selectedImage=images.length?images.length-1:-1;sync()};function renderLayers(){let html=images.map((im,i)=>`<div class="layer ${i===selectedImage?'on':''}" data-li="${i}"><span>${i+1}. ${im.name}</span><span>${im.visible?'ON':'OFF'}</span></div>`).join('');$('imageLayers').innerHTML=html;$('miniLayers').innerHTML=html}$('imageLayers').onclick=$('miniLayers').onclick=e=>{let l=e.target.closest('[data-li]');if(!l)return;selectedImage=+l.dataset.li;let im=images[selectedImage];$('imgOp').value=im.opacity*100;$('blend').value=im.blend;$('imgSelected').textContent=im.name;sync()};$('imgOp').oninput=e=>{if(selectedImage<0)return;images[selectedImage].opacity=+e.target.value/100;sync()};$('blend').onchange=e=>{if(selectedImage<0)return;images[selectedImage].blend=e.target.value;sync()};$('fwd').onclick=()=>moveLayer(1);$('back').onclick=()=>moveLayer(-1);function moveLayer(d){let n=selectedImage+d;if(selectedImage<0||n<0||n>=images.length)return;[images[selectedImage],images[n]]=[images[n],images[selectedImage]];selectedImage=n;sync()}$('hide').onclick=()=>{if(selectedImage<0)return;images[selectedImage].visible=!images[selectedImage].visible;sync()};$('fit').onclick=()=>{if(selectedImage<0)return;Object.assign(images[selectedImage],{x:0,y:0,w:1,h:1});sync()};
function dl(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}function jsonDl(o,n){dl(new Blob([JSON.stringify(o,null,2)],{type:'application/json'}),n)}function hash(s){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0}function mulberry(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function state(i=0){let rng=mulberry(hash($('seed').value+':'+i)),ms=JSON.parse(JSON.stringify(modules)),b=$('lockBg').checked?bg:P[Math.floor(rng()*P.length)];if($('cycleColors').checked)ms.forEach(m=>m.fill=P[Math.floor(rng()*P.length)]);if($('cycleTextures').checked)ms.forEach(m=>m.texture=texNames[Math.floor(rng()*texNames.length)]);return{bg:b,modules:ms,index:i,name:$('collectionName').value+' #'+String(i+1).padStart(4,'0'),constraint:'canonical-opepen-8x8'}}
function svgModule(m){let f=m.fill==='transparent'?'none':m.fill,st=m.stroke&&m.stroke!=='transparent'?` stroke="${m.stroke}" stroke-width="4"`:'',x=m.x*100,y=m.y*100;if(m.type==='left-eye')return `<path d="M ${x+100} ${y} A 100 100 0 1 1 ${x} ${y+100} L ${x} ${y} Z" fill="${f}"${st}/>`;if(m.type==='right-eye')return `<circle cx="${x+100}" cy="${y+100}" r="100" fill="${f}"${st}/>`;if(m.type==='mouth')return `<path d="M ${x+100} ${y+200} A 100 100 0 0 1 ${x} ${y+100} L ${x} ${y} L ${x+400} ${y} L ${x+400} ${y+100} A 100 100 0 0 1 ${x+300} ${y+200} Z" fill="${f}"${st}/>`;if(m.type==='torso')return `<path d="M ${x} ${y+100} A 100 100 0 0 1 ${x+100} ${y} L ${x+300} ${y} A 100 100 0 0 1 ${x+400} ${y+100} Z" fill="${f}"${st}/>`;return `<rect x="${x}" y="${y}" width="${m.w*100}" height="${m.h*100}" fill="${f}"${st}/>`}
function svgText(s=state(0)){return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800"><rect width="800" height="800" fill="${s.bg}"/>${s.modules.map(svgModule).join('')}</svg>`}
$('saveSvg').onclick=()=>dl(new Blob([svgText()],{type:'image/svg+xml'}),'opepen-schematic.svg');$('saveJpg').onclick=()=>exportRaster(1200,'image/jpeg','opepen.jpg',.96);function exportRaster(size,type,name,q=.96,s=state(0)){let oc=document.createElement('canvas');oc.width=oc.height=size;renderTo(oc.getContext('2d'),size,s,true);oc.toBlob(b=>dl(b,name),type,q)}
$('previewBatch').onclick=()=>{let n=Math.min(48,+$('previewCount').value||12),g=$('previewGrid');g.innerHTML='';for(let i=0;i<n;i++){let oc=document.createElement('canvas');oc.width=oc.height=180;drawState(oc.getContext('2d'),180,state(i),false);let im=document.createElement('img');im.src=oc.toDataURL('image/jpeg',.82);g.appendChild(im)}$('previewStat').textContent=n+' ITEMS'};
$('exportCollection').onclick=()=>jsonDl({name:$('collectionName').value,supply:+$('supply').value,seed:$('seed').value,constraint:'canonical-opepen-8x8',schematic:'/opepen-schematics.svg'},'collection.json');
$('exportTraits').onclick=()=>{let n=+$('supply').value,rows=['token,background,left_eye,right_eye,mouth,torso'];for(let i=0;i<n;i++){let s=state(i);rows.push([i+1,s.bg,...s.modules.slice(0,4).map(m=>m.fill)].join(','))}dl(new Blob([rows.join('\n')],{type:'text/csv'}),'traits.csv')};
$('exportSvgBundle').onclick=async()=>{let z=new JSZip(),n=Math.min(1000,+$('supply').value);for(let i=0;i<n;i++)z.file(String(i+1).padStart(4,'0')+'.svg',svgText(state(i)));dl(await z.generateAsync({type:'blob'}),'svg-bundle.zip')};
$('exportBatch').onclick=async()=>{if(typeof JSZip==='undefined'){alert('ZIP exporter did not load. Check your connection and refresh.');return}let z=new JSZip(),n=Math.max(1,+$('supply').value||1),lim=Math.min(n,500);$('progressPct').textContent='0%';$('progressBar').style.width='0%';$('progressText').textContent='EXPORTING…';for(let i=0;i<lim;i++){let s=state(i),oc=document.createElement('canvas');oc.width=oc.height=1200;drawState(oc.getContext('2d'),1200,s,false);let blob=await new Promise(r=>oc.toBlob(r,'image/jpeg',.95));z.file('images/'+String(i+1).padStart(4,'0')+'.jpg',blob);z.file('metadata/'+String(i+1).padStart(4,'0')+'.json',JSON.stringify({name:s.name,image:String(i+1).padStart(4,'0')+'.jpg',attributes:s.modules.map(m=>({trait_type:m.name,value:m.fill})),constraint:'canonical-opepen-8x8'},null,2));let pct=Math.round((i+1)/lim*100);$('progressPct').textContent=pct+'%';$('progressBar').style.width=pct+'%';$('progressText').textContent=`${i+1} / ${lim}`}dl(await z.generateAsync({type:'blob'}),'opepen-collection.zip');$('progressText').textContent=n>lim?`COMPLETE · FIRST ${lim} EXPORTED IN BROWSER-SAFE ZIP`:'COMPLETE'};
$('lockBg').onchange=()=>{$('lockBgHex').textContent=bg.toUpperCase()};sync();